create table vehicles(
    id bigint primary key,
    url text,
    region varchar(255),
    region_url text,
    price integer,
    year integer,
    manufacturer varchar(255),
    model varchar(255),
    condition varchar(50),
    cylinders varchar(50),
    fuel varchar(50),
    odometer integer,
    title_status varchar(50),
    transmission varchar(50),
    vin varchar(50),
    drive varchar(50),
    size varchar(50),
    type varchar(50),
    paint_color varchar(50),
    image_url text,
    description text,
    country text,
    state varchar(50),
    lat double precision,
    long double precision
)